# SOPS Configuration for Obsidian LiveSync
creation_rules:
  - path_regex: .*\.(yaml|yml|json|env|ini)$
    age: >-
      age1tyqgw9lv8r7p2ewjznt8rw8050ysp63vletzy2w3hxfa7dzqdu6qdqwsl4
    encrypted_regex: '^(data|stringData|password|token|key|secret|apiKey|apiToken|credential)$'
