# SOPS Configuration for Obsidian LiveSync
creation_rules:
  - path_regex: .*\.(yaml|yml|json|env|ini)$
    age: >-
      age13gwk9j9ddstm8ss9n2u8nx6ruh6zgafsapepmjz353tuarwu23hsqffl6t
    encrypted_regex: '^(data|stringData|password|token|key|secret|apiKey|apiToken|credential)$'
