---
apiVersion: v1
kind: Namespace
metadata:
  name: obsidian-livesync
  labels:
    name: obsidian-livesync

---
apiVersion: v1
kind: Secret
metadata:
  name: couchdb-credentials
  namespace: obsidian-livesync
type: Opaque
data:
  # Base64-encode your values: 
  # echo -n 'your_username' | base64
  # echo -n 'your_password' | base64
  username: YWRtaW4=  # Replace with actual base64-encoded username
  password: YWRtaW4=  # Replace with actual base64-encoded password

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data
  namespace: obsidian-livesync
  labels:
    app: couchdb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-encrypted  # Using encrypted storage class
  resources:
    requests:
      storage: 20Gi  # Increased from 10Gi for better headroom

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-config
  namespace: obsidian-livesync
  labels:
    app: couchdb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-encrypted  # Using encrypted storage class
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  namespace: obsidian-livesync
  labels:
    app: couchdb
    component: database
spec:
  replicas: 1
  strategy:
    type: Recreate  # Required for single pod with ReadWriteOnce volumes
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
        component: database
    spec:
      securityContext:
        fsGroup: 5984
        runAsNonRoot: true
        runAsUser: 5984
      containers:
        - name: couchdb
          image: couchdb:3.5
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5984
              protocol: TCP
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb-credentials
                  key: username
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-credentials
                  key: password
            - name: COUCHDB_SECRET
              valueFrom:
                secretKeyRef:
                  name: couchdb-credentials
                  key: password  # Reuse password as secret, or create separate secret
            - name: TZ
              value: 'UTC'  # Changed to UTC for consistency
          volumeMounts:
            - name: couchdb-data
              mountPath: /opt/couchdb/data
            - name: couchdb-config
              mountPath: /opt/couchdb/etc/local.d
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
            limits:
              memory: '2Gi'
              cpu: '2000m'
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - curl -f -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} http://127.0.0.1:5984/_up
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - curl -f -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} http://127.0.0.1:5984/_up
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
            successThreshold: 1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false  # CouchDB needs write access
      volumes:
        - name: couchdb-data
          persistentVolumeClaim:
            claimName: couchdb-data
        - name: couchdb-config
          persistentVolumeClaim:
            claimName: couchdb-config

---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-service
  namespace: obsidian-livesync
  labels:
    app: couchdb
spec:
  type: NodePort
  selector:
    app: couchdb
  ports:
    - name: http
      port: 5984
      targetPort: http
      protocol: TCP
      nodePort: 30984
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

---
# Optional: LoadBalancer Service (uncomment if using MetalLB)
# Uncomment this section and comment out the NodePort service above to use MetalLB
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: couchdb-service
#   namespace: obsidian-livesync
#   labels:
#     app: couchdb
# spec:
#   type: LoadBalancer
#   selector:
#     app: couchdb
#   ports:
#     - name: http
#       port: 5984
#       targetPort: http
#       protocol: TCP
#   sessionAffinity: ClientIP
#   sessionAffinityConfig:
#     clientIP:
#       timeoutSeconds: 10800

---
# Optional: Ingress for HTTPS access with Cert Manager and nip.io
# Uncomment and customize this section if you want HTTPS access via Ingress
# 
# To get your IP address for nip.io:
#   - From homeserver: ip addr show | grep "inet " | grep -v 127.0.0.1
#   - Or use: hostname -I | awk '{print $1}'
# 
# Replace YOUR_IP below with your homeserver's IP (e.g., 192.168.1.100)
# Then uncomment this entire section
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: couchdb-ingress
#   namespace: obsidian-livesync
#   labels:
#     app: couchdb
#   annotations:
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
#     nginx.ingress.kubernetes.io/ssl-redirect: "true"
#     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#     nginx.ingress.kubernetes.io/proxy-body-size: "4294967296"  # 4GB max
#     nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
#     nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
# spec:
#   ingressClassName: nginx
#   tls:
#     - hosts:
#         - YOUR_IP.nip.io  # Replace YOUR_IP with your actual IP (e.g., 192.168.1.100.nip.io)
#       secretName: couchdb-tls
#   rules:
#     - host: YOUR_IP.nip.io  # Replace YOUR_IP with your actual IP (e.g., 192.168.1.100.nip.io)
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: couchdb-service
#                 port:
#                   number: 5984